"""empty message

Revision ID: ee1ea6cb6bed
Revises: 
Create Date: 2023-06-08 14:51:32.961902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1ea6cb6bed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.drop_constraint('shows_venue_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('shows_artist_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'venues', ['venue_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'artists', ['artist_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('shows_artist_id_fkey', 'artists', ['artist_id'], ['id'])
        batch_op.create_foreign_key('shows_venue_id_fkey', 'venues', ['venue_id'], ['id'])

    # ### end Alembic commands ###
